---
- hosts: all
  tasks:
    - name: Install basic list of packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - zsh
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      become: yes

    - name: Add docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      become: yes

    - name: Add docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      become: yes

    - name: Install Docker packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      become: yes

    - name: Create docker group
      group:
        name: docker

    - name: Add user to docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes
      become: yes

    - name: Ensure docker service is enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: +x
      become: yes

    - name: Add docker GPG key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      become: yes

    - name: Add postgres apt repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main"
      become: yes

    - name: Install postgres packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - postgresql-client
      become: yes
