# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.memory = 8192
  end

  config.disksize.size = '64GB'

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision.yml"
  end
end
